acme_calculator_homepage:
    path:     /
    defaults: { _controller: AcmeCalculatorBundle:Calculator:index }

calculator:
    path:     /calculator/{opt}/{op1}/{op2}
    defaults: { _controller: AcmeCalculatorBundle:Calculator:calculate }